[CmdletBinding()]
param(
    [switch]$DryRun,
    [switch]$Revert,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$Feature = 'options-view-polish'
$RepoRoot = (Get-Location).Path

if (-not (Test-Path -LiteralPath (Join-Path $RepoRoot 'CMakeLists.txt') -PathType Leaf)) {
    throw "FAIL ROOT: Run this script from the Sample Box repository root (CMakeLists.txt was not found)."
}

$Branch = (git -C $RepoRoot branch --show-current 2>$null)
if (($Branch -eq 'main' -or $Branch -eq 'master') -and -not $Force) {
    throw "FAIL BRANCH: Refusing to write on '$Branch'. Switch to a feature branch or pass -Force explicitly."
}

$BackupRoot = Join-Path $RepoRoot ('.git\' + $Feature + '-patch-backup')
$ManifestPath = Join-Path $BackupRoot 'latest-manifest.txt'

if ($Revert) {
    if (-not (Test-Path -LiteralPath $ManifestPath -PathType Leaf)) { throw "FAIL REVERT: No manifest found at $ManifestPath" }
    foreach ($Line in (Get-Content -LiteralPath $ManifestPath)) {
        if ([string]::IsNullOrWhiteSpace($Line)) { continue }
        $Parts = $Line -split '\t', 3
        if ($Parts[0] -ne 'MODIFIED') { throw "FAIL REVERT: Unknown manifest mode '$($Parts[0])'" }
        Copy-Item -LiteralPath $Parts[2] -Destination (Join-Path $RepoRoot $Parts[1]) -Force
        Write-Host "OK REVERT $($Parts[1])"
    }
    exit 0
}

$Timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$ThisBackup = Join-Path $BackupRoot $Timestamp
$Manifest = New-Object System.Collections.Generic.List[string]
$HadFailure = $false

function Write-Replacement {
    param([string]$EditId, [string]$RelativePath, [string]$Base64Content)
    $Target = Join-Path $RepoRoot $RelativePath
    if (-not (Test-Path -LiteralPath $Target -PathType Leaf)) {
        Write-Host "FAIL ${EditId}: Missing expected file $RelativePath" -ForegroundColor Red
        $script:HadFailure = $true
        return
    }
    $NewText = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($Base64Content))
    $OldBytes = [System.IO.File]::ReadAllBytes($Target)
    $HasBom = $OldBytes.Length -ge 3 -and $OldBytes[0] -eq 0xEF -and $OldBytes[1] -eq 0xBB -and $OldBytes[2] -eq 0xBF
    $OldText = [System.Text.Encoding]::UTF8.GetString($OldBytes)
    if ($HasBom) { $OldText = $OldText.TrimStart([char]0xFEFF) }
    $NormalizedNew = if ($OldText.Contains("`r`n")) { $NewText -replace "`n", "`r`n" } else { $NewText }
    if ($OldText -eq $NormalizedNew) { Write-Host "SKIP ${EditId}: $RelativePath already matches this patch" -ForegroundColor Yellow; return }
    if ($DryRun) { Write-Host "OK DRYRUN ${EditId}: replace $RelativePath"; return }
    $Backup = Join-Path $ThisBackup $RelativePath
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Backup) | Out-Null
    Copy-Item -LiteralPath $Target -Destination $Backup -Force
    $Manifest.Add("MODIFIED`t$RelativePath`t$Backup")
    [System.IO.File]::WriteAllText($Target, $NormalizedNew, (New-Object System.Text.UTF8Encoding($HasBom)))
    Write-Host "OK ${EditId}: replaced $RelativePath" -ForegroundColor Green
}

Write-Replacement -EditId 'E01' -RelativePath 'src/UI/BrowserView.h' -Base64Content 'I3ByYWdtYSBvbmNlCgojaW5jbHVkZSAiLi4vY29yZS9Ccm93c2VTdGF0ZS5oIgoKI2luY2x1ZGUgPGp1Y2VfZ3VpX2Jhc2ljcy9qdWNlX2d1aV9iYXNpY3MuaD4KCiNpbmNsdWRlIDxmaWxlc3lzdGVtPgojaW5jbHVkZSA8ZnVuY3Rpb25hbD4KI2luY2x1ZGUgPG1lbW9yeT4KCm5hbWVzcGFjZSBzYW1wbGVib3gKewpjbGFzcyBDb3ZlckFydENhcm91c2VsOwoKY2xhc3MgQnJvd3NlclZpZXcgZmluYWwgOiBwdWJsaWMganVjZTo6Q29tcG9uZW50LAogICAgICAgICAgICAgICAgICAgICAgICAgIHByaXZhdGUgQnJvd3NlU3RhdGU6Okxpc3RlbmVyCnsKcHVibGljOgogICAgdXNpbmcgU2FtcGxlU2VsZWN0ZWQgPSBzdGQ6OmZ1bmN0aW9uPHZvaWQoY29uc3Qgc3RkOjpmaWxlc3lzdGVtOjpwYXRoJik+OwoKICAgIEJyb3dzZXJWaWV3KEJyb3dzZVN0YXRlJiBicm93c2VTdGF0ZSwgU2FtcGxlU2VsZWN0ZWQgb25TYW1wbGVTZWxlY3RlZCA9IHt9KTsKICAgIH5Ccm93c2VyVmlldygpIG92ZXJyaWRlOwoKICAgIHZvaWQgcmVmcmVzaCgpOwoKICAgIHZvaWQgcGFpbnQoanVjZTo6R3JhcGhpY3MmIGdyYXBoaWNzKSBvdmVycmlkZTsKICAgIHZvaWQgcmVzaXplZCgpIG92ZXJyaWRlOwoKcHJpdmF0ZToKICAgIHZvaWQgYnJvd3NlVmlld01vZGVDaGFuZ2VkKCkgb3ZlcnJpZGU7CiAgICB2b2lkIHVwZGF0ZUFjdGl2ZVZpZXcoKTsKCiAgICBCcm93c2VTdGF0ZSYgc3RhdGU7CiAgICBzdGQ6OnVuaXF1ZV9wdHI8Q292ZXJBcnRDYXJvdXNlbD4gY2Fyb3VzZWw7Cn07Cn0K'
Write-Replacement -EditId 'E02' -RelativePath 'src/UI/BrowserView.cpp' -Base64Content 'I2luY2x1ZGUgIkJyb3dzZXJWaWV3LmgiCgojaW5jbHVkZSAiQ292ZXJBcnRDYXJvdXNlbC5oIgojaW5jbHVkZSAiVGhlbWUuaCIKCiNpbmNsdWRlIDx1dGlsaXR5PgoKbmFtZXNwYWNlIHNhbXBsZWJveAp7CkJyb3dzZXJWaWV3OjpCcm93c2VyVmlldyhCcm93c2VTdGF0ZSYgYnJvd3NlU3RhdGUsIFNhbXBsZVNlbGVjdGVkIG9uU2FtcGxlU2VsZWN0ZWQpCiAgICA6IHN0YXRlKGJyb3dzZVN0YXRlKSwKICAgICAgY2Fyb3VzZWwoc3RkOjptYWtlX3VuaXF1ZTxDb3ZlckFydENhcm91c2VsPihicm93c2VTdGF0ZSwgc3RkOjptb3ZlKG9uU2FtcGxlU2VsZWN0ZWQpKSkKewogICAgc3RhdGUuYWRkTGlzdGVuZXIodGhpcyk7CiAgICBhZGRBbmRNYWtlVmlzaWJsZSgqY2Fyb3VzZWwpOwogICAgdXBkYXRlQWN0aXZlVmlldygpOwp9CgpCcm93c2VyVmlldzo6fkJyb3dzZXJWaWV3KCkKewogICAgc3RhdGUucmVtb3ZlTGlzdGVuZXIodGhpcyk7Cn0KCnZvaWQgQnJvd3NlclZpZXc6OnJlZnJlc2goKQp7CiAgICBjYXJvdXNlbC0+cmVmcmVzaCgpOwogICAgdXBkYXRlQWN0aXZlVmlldygpOwp9Cgp2b2lkIEJyb3dzZXJWaWV3OjpwYWludChqdWNlOjpHcmFwaGljcyYgZ3JhcGhpY3MpCnsKICAgIGdyYXBoaWNzLmZpbGxBbGwodGhlbWU6OmJhY2tncm91bmQpOwoKICAgIGlmIChzdGF0ZS5wYWNrVmlld01vZGUgPT0gUGFja1ZpZXdNb2RlOjpjb3ZlckZsb3cpCiAgICAgICAgcmV0dXJuOwoKICAgIGNvbnN0IGF1dG8gbW9kZU5hbWUgPSBzdGF0ZS5wYWNrVmlld01vZGUgPT0gUGFja1ZpZXdNb2RlOjpncmlkID8gIkdyaWQiIDogIkxpc3QiOwogICAgY29uc3QgYXV0byBib3VuZHMgPSBnZXRMb2NhbEJvdW5kcygpLnRvRmxvYXQoKTsKCiAgICBncmFwaGljcy5zZXRDb2xvdXIodGhlbWU6OnRleHRQcmltYXJ5KTsKICAgIGdyYXBoaWNzLnNldEZvbnQoMjAuMGYpOwogICAgZ3JhcGhpY3MuZHJhd1RleHQoanVjZTo6U3RyaW5nKG1vZGVOYW1lKSArICIgdmlldyBpcyB1bmRlciBjb25zdHJ1Y3Rpb24iLAogICAgICAgICAgICAgICAgICAgICAgYm91bmRzLndpdGhUcmltbWVkQm90dG9tKDIyLjBmKSwKICAgICAgICAgICAgICAgICAgICAgIGp1Y2U6Okp1c3RpZmljYXRpb246OmNlbnRyZWQpOwoKICAgIGdyYXBoaWNzLnNldENvbG91cih0aGVtZTo6dGV4dFNlY29uZGFyeSk7CiAgICBncmFwaGljcy5zZXRGb250KDE0LjBmKTsKICAgIGdyYXBoaWNzLmRyYXdUZXh0KCJVc2UgQ2Fyb3VzZWwgaW4gT3B0aW9ucyB0byBicm93c2UgcGFja3MuIiwKICAgICAgICAgICAgICAgICAgICAgIGJvdW5kcy53aXRoVHJpbW1lZFRvcCgyMi4wZiksCiAgICAgICAgICAgICAgICAgICAgICBqdWNlOjpKdXN0aWZpY2F0aW9uOjpjZW50cmVkKTsKfQoKdm9pZCBCcm93c2VyVmlldzo6cmVzaXplZCgpCnsKICAgIGNhcm91c2VsLT5zZXRCb3VuZHMoZ2V0TG9jYWxCb3VuZHMoKSk7Cn0KCnZvaWQgQnJvd3NlclZpZXc6OmJyb3dzZVZpZXdNb2RlQ2hhbmdlZCgpCnsKICAgIHVwZGF0ZUFjdGl2ZVZpZXcoKTsKfQoKdm9pZCBCcm93c2VyVmlldzo6dXBkYXRlQWN0aXZlVmlldygpCnsKICAgIGNvbnN0IGJvb2wgc2hvd0Nhcm91c2VsID0gc3RhdGUucGFja1ZpZXdNb2RlID09IFBhY2tWaWV3TW9kZTo6Y292ZXJGbG93OwogICAgY2Fyb3VzZWwtPnNldFZpc2libGUoc2hvd0Nhcm91c2VsKTsKICAgIHJlcGFpbnQoKTsKfQp9Cg=='
Write-Replacement -EditId 'E03' -RelativePath 'src/UI/CoverArtCard.cpp' -Base64Content 'I2luY2x1ZGUgIkNvdmVyQXJ0Q2FyZC5oIgoKI2luY2x1ZGUgIkFydHdvcmtDYWNoZS5oIgojaW5jbHVkZSAiVGhlbWUuaCIKCiNpbmNsdWRlIDxjbWF0aD4KI2luY2x1ZGUgPHV0aWxpdHk+CgpuYW1lc3BhY2Ugc2FtcGxlYm94CnsKQ292ZXJBcnRDYXJkOjpDb3ZlckFydENhcmQoQXJ0d29ya0NhY2hlJiBjYWNoZSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgc3RkOjpmdW5jdGlvbjx2b2lkKHN0ZDo6c2l6ZV90KT4gY2xpY2tDYWxsYmFjaykKICAgIDogYXJ0d29ya0NhY2hlKGNhY2hlKSwKICAgICAgb25QYWNrQ2xpY2tlZChzdGQ6Om1vdmUoY2xpY2tDYWxsYmFjaykpCnsKfQoKdm9pZCBDb3ZlckFydENhcmQ6OmJpbmRUb1BhY2soTGlicmFyeVNuYXBzaG90UHRyIHNuYXBzaG90LCBzdGQ6OnNpemVfdCBpbmRleE9mUGFjaykKewogICAgY29uc3QgYm9vbCBwYWNrQ2hhbmdlZCA9IChsaWJyYXJ5U25hcHNob3QgIT0gc25hcHNob3QpIHx8IChwYWNrSW5kZXggIT0gaW5kZXhPZlBhY2spOwogICAgbGlicmFyeVNuYXBzaG90ID0gc3RkOjptb3ZlKHNuYXBzaG90KTsKICAgIHBhY2tJbmRleCA9IGluZGV4T2ZQYWNrOwoKICAgIGlmIChwYWNrQ2hhbmdlZCkKICAgICAgICByZXBhaW50KCk7Cn0KCnZvaWQgQ292ZXJBcnRDYXJkOjptb3VzZURvd24oY29uc3QganVjZTo6TW91c2VFdmVudCYpCnsKICAgIGlmIChvblBhY2tDbGlja2VkICYmIGhhc1ZhbGlkUGFjaygpKQogICAgICAgIG9uUGFja0NsaWNrZWQocGFja0luZGV4KTsKfQoKdm9pZCBDb3ZlckFydENhcmQ6OnNldFZpc3VhbFN0YXRlKGZsb2F0IG5ld1NjYWxlLCBmbG9hdCBuZXdPcGFjaXR5LCBib29sIGlzU2VsZWN0ZWQpCnsKICAgIGNvbnN0IGF1dG8gY2hhbmdlZCA9IHN0ZDo6YWJzKG5ld1NjYWxlIC0gc2NhbGUpID4gMC4wMDFmCiAgICAgICAgICAgICAgICAgICAgICB8fCBzdGQ6OmFicyhuZXdPcGFjaXR5IC0gb3BhY2l0eSkgPiAwLjAwMWYKICAgICAgICAgICAgICAgICAgICAgIHx8IGlzU2VsZWN0ZWQgIT0gc2VsZWN0ZWQ7CgogICAgc2NhbGUgPSBuZXdTY2FsZTsKICAgIG9wYWNpdHkgPSBuZXdPcGFjaXR5OwogICAgc2VsZWN0ZWQgPSBpc1NlbGVjdGVkOwoKICAgIGlmIChjaGFuZ2VkKQogICAgICAgIHJlcGFpbnQoKTsKfQoKdm9pZCBDb3ZlckFydENhcmQ6OnNldFNob3dUaXRsZShib29sIHNob3cpCnsKICAgIGlmIChzaG93VGl0bGUgPT0gc2hvdykKICAgICAgICByZXR1cm47CiAgICBzaG93VGl0bGUgPSBzaG93OwogICAgcmVwYWludCgpOwp9Cgp2b2lkIENvdmVyQXJ0Q2FyZDo6cGFpbnQoanVjZTo6R3JhcGhpY3MmIGdyYXBoaWNzKQp7CiAgICBjb25zdCBhdXRvKiBwYWNrID0gZ2V0UGFjaygpOwogICAgaWYgKHBhY2sgPT0gbnVsbHB0cikKICAgICAgICByZXR1cm47CgogICAgY29uc3QgYXV0byBib3VuZHMgPSBnZXRMb2NhbEJvdW5kcygpLnRvRmxvYXQoKTsKICAgIGdyYXBoaWNzLnNldE9wYWNpdHkob3BhY2l0eSk7CiAgICBncmFwaGljcy5zZXRDb2xvdXIodGhlbWU6OnN1cmZhY2UpOwogICAgZ3JhcGhpY3MuZmlsbFJvdW5kZWRSZWN0YW5nbGUoYm91bmRzLCB0aGVtZTo6Y2FyZENvcm5lclJhZGl1cyk7CgogICAgY29uc3QgYXV0byBhcnR3b3JrQm91bmRzID0gc2hvd1RpdGxlCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPyBib3VuZHMucmVkdWNlZCgxMi4wZikud2l0aFRyaW1tZWRCb3R0b20oNDYuMGYpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgOiBib3VuZHMucmVkdWNlZCgxMi4wZik7CiAgICBjb25zdGV4cHIgaW50IGNvdmVyRmxvd1RodW1ibmFpbFNpemUgPSAzMjA7CiAgICBjb25zdCBhdXRvIHRodW1ibmFpbFdpZHRoID0gY292ZXJGbG93VGh1bWJuYWlsU2l6ZTsKICAgIGNvbnN0IGF1dG8gdGh1bWJuYWlsSGVpZ2h0ID0gY292ZXJGbG93VGh1bWJuYWlsU2l6ZTsKCiAgICBjb25zdCBqdWNlOjpDb21wb25lbnQ6OlNhZmVQb2ludGVyPENvdmVyQXJ0Q2FyZD4gc2FmZVRoaXModGhpcyk7CiAgICBjb25zdCBhdXRvIGNhcHR1cmVkSW5kZXggPSBwYWNrSW5kZXg7CgogICAgY29uc3QgYXV0byBpbWFnZSA9IGFydHdvcmtDYWNoZS5nZXRUaHVtYm5haWwoCiAgICAgICAgcGFjay0+Y292ZXJBcnRQYXRoLAogICAgICAgIHRodW1ibmFpbFdpZHRoLAogICAgICAgIHRodW1ibmFpbEhlaWdodCwKICAgICAgICBbc2FmZVRoaXMsIGNhcHR1cmVkSW5kZXhdKCkKICAgICAgICB7CiAgICAgICAgICAgIC8vIFZlcmlmeSBjb21wb25lbnQgaXMgc3RpbGwgYm91bmQgdG8gdGhlIHNhbWUgcGFjawogICAgICAgICAgICBpZiAoc2FmZVRoaXMgIT0gbnVsbHB0ciAmJiBzYWZlVGhpcy0+cGFja0luZGV4ID09IGNhcHR1cmVkSW5kZXgpCiAgICAgICAgICAgICAgICBzYWZlVGhpcy0+cmVwYWludCgpOwogICAgICAgIH0pOwoKICAgIGdyYXBoaWNzLmRyYXdJbWFnZVdpdGhpbihpbWFnZSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICBhcnR3b3JrQm91bmRzLmdldFgoKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICBhcnR3b3JrQm91bmRzLmdldFkoKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICBhcnR3b3JrQm91bmRzLmdldFdpZHRoKCksCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYXJ0d29ya0JvdW5kcy5nZXRIZWlnaHQoKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICBqdWNlOjpSZWN0YW5nbGVQbGFjZW1lbnQ6OmNlbnRyZWQpOwoKICAgIGlmIChzaG93VGl0bGUpCiAgICB7CiAgICAgICAgZ3JhcGhpY3Muc2V0Q29sb3VyKHRoZW1lOjp0ZXh0UHJpbWFyeSk7CiAgICBncmFwaGljcy5zZXRGb250KHNlbGVjdGVkID8gMTcuMGYgOiAxNS4wZik7CiAgICBncmFwaGljcy5kcmF3Rml0dGVkVGV4dChwYWNrLT50aXRsZSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGdldExvY2FsQm91bmRzKCkucmVkdWNlZCgxMikucmVtb3ZlRnJvbUJvdHRvbSgzNCksCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBqdWNlOjpKdXN0aWZpY2F0aW9uOjpjZW50cmVkLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgMik7CiAgICB9Cn0KfQ=='
Write-Replacement -EditId 'E04' -RelativePath 'src/UI/OptionsComponent.cpp' -Base64Content 'I2luY2x1ZGUgIk9wdGlvbnNDb21wb25lbnQuaCIKI2luY2x1ZGUgIlRoZW1lLmgiCgpuYW1lc3BhY2Ugc2FtcGxlYm94CnsKT3B0aW9uc0NvbXBvbmVudDo6T3B0aW9uc0NvbXBvbmVudCgpCnsKICAgIHZpZXdMYWJlbC5zZXRUZXh0KCJEZWZhdWx0IHZpZXciLCBqdWNlOjpkb250U2VuZE5vdGlmaWNhdGlvbik7CiAgICB2b2x1bWVMYWJlbC5zZXRUZXh0KCJQcmV2aWV3IHZvbHVtZSIsIGp1Y2U6OmRvbnRTZW5kTm90aWZpY2F0aW9uKTsKCiAgICB2aWV3Q29tYm8uYWRkSXRlbSgiTGlzdCAodW5kZXIgY29uc3RydWN0aW9uKSIsIDEpOwogICAgdmlld0NvbWJvLmFkZEl0ZW0oIkdyaWQgKHVuZGVyIGNvbnN0cnVjdGlvbikiLCAyKTsKICAgIHZpZXdDb21iby5hZGRJdGVtKCJDYXJvdXNlbCIsIDMpOwogICAgdmlld0NvbWJvLm9uQ2hhbmdlID0gW3RoaXNdCiAgICB7CiAgICAgICAgb3B0aW9ucy5kZWZhdWx0Vmlld01vZGUgPSBzdGF0aWNfY2FzdDxQYWNrVmlld01vZGU+KHZpZXdDb21iby5nZXRTZWxlY3RlZElkKCkgLSAxKTsKICAgICAgICBub3RpZnkoKTsKICAgIH07CgogICAgdGl0bGVzVG9nZ2xlLnNldENvbG91cihqdWNlOjpUb2dnbGVCdXR0b246OnRleHRDb2xvdXJJZCwgdGhlbWU6OnRleHRQcmltYXJ5KTsKICAgIHRpdGxlc1RvZ2dsZS5vbkNsaWNrID0gW3RoaXNdCiAgICB7CiAgICAgICAgb3B0aW9ucy5zaG93Q292ZXJUaXRsZXMgPSB0aXRsZXNUb2dnbGUuZ2V0VG9nZ2xlU3RhdGUoKTsKICAgICAgICBub3RpZnkoKTsKICAgIH07CgogICAgdm9sdW1lU2xpZGVyLnNldFNsaWRlclN0eWxlKGp1Y2U6OlNsaWRlcjo6TGluZWFySG9yaXpvbnRhbCk7CiAgICB2b2x1bWVTbGlkZXIuc2V0UmFuZ2UoMC4wLCAxLjAsIDAuMDEpOwogICAgdm9sdW1lU2xpZGVyLnNldFRleHRCb3hTdHlsZShqdWNlOjpTbGlkZXI6OlRleHRCb3hSaWdodCwgZmFsc2UsIDU2LCAyMik7CiAgICB2b2x1bWVTbGlkZXIuc2V0VGV4dEJveElzRWRpdGFibGUoZmFsc2UpOwogICAgdm9sdW1lU2xpZGVyLnRleHRGcm9tVmFsdWVGdW5jdGlvbiA9IFtdKGRvdWJsZSB2KQogICAgewogICAgICAgIHJldHVybiBqdWNlOjpTdHJpbmcoanVjZTo6cm91bmRUb0ludCh2ICogMTAwLjApKSArICIlIjsKICAgIH07CiAgICB2b2x1bWVTbGlkZXIub25WYWx1ZUNoYW5nZSA9IFt0aGlzXQogICAgewogICAgICAgIG9wdGlvbnMucHJldmlld1ZvbHVtZSA9IHN0YXRpY19jYXN0PGZsb2F0Pih2b2x1bWVTbGlkZXIuZ2V0VmFsdWUoKSk7CiAgICAgICAgbm90aWZ5KCk7CiAgICB9OwoKICAgIGFkZEFuZE1ha2VWaXNpYmxlKHZpZXdMYWJlbCk7CiAgICBhZGRBbmRNYWtlVmlzaWJsZSh2b2x1bWVMYWJlbCk7CiAgICBhZGRBbmRNYWtlVmlzaWJsZSh2aWV3Q29tYm8pOwogICAgYWRkQW5kTWFrZVZpc2libGUodGl0bGVzVG9nZ2xlKTsKICAgIGFkZEFuZE1ha2VWaXNpYmxlKHZvbHVtZVNsaWRlcik7CgogICAgc2V0T3B0aW9ucyhvcHRpb25zKTsKfQoKdm9pZCBPcHRpb25zQ29tcG9uZW50OjpzZXRPcHRpb25zKGNvbnN0IEFwcE9wdGlvbnMmIG5ld09wdGlvbnMpCnsKICAgIG9wdGlvbnMgPSBuZXdPcHRpb25zOwogICAgdmlld0NvbWJvLnNldFNlbGVjdGVkSWQoc3RhdGljX2Nhc3Q8aW50PihvcHRpb25zLmRlZmF1bHRWaWV3TW9kZSkgKyAxLCBqdWNlOjpkb250U2VuZE5vdGlmaWNhdGlvbik7CiAgICB0aXRsZXNUb2dnbGUuc2V0VG9nZ2xlU3RhdGUob3B0aW9ucy5zaG93Q292ZXJUaXRsZXMsIGp1Y2U6OmRvbnRTZW5kTm90aWZpY2F0aW9uKTsKICAgIHZvbHVtZVNsaWRlci5zZXRWYWx1ZShzdGF0aWNfY2FzdDxkb3VibGU+KG9wdGlvbnMucHJldmlld1ZvbHVtZSksIGp1Y2U6OmRvbnRTZW5kTm90aWZpY2F0aW9uKTsKfQoKdm9pZCBPcHRpb25zQ29tcG9uZW50OjpwYWludChqdWNlOjpHcmFwaGljcyYgZykKewogICAgZy5maWxsQWxsKHRoZW1lOjpiYWNrZ3JvdW5kKTsKfQoKdm9pZCBPcHRpb25zQ29tcG9uZW50OjpyZXNpemVkKCkKewogICAgYXV0byBhcmVhID0gZ2V0TG9jYWxCb3VuZHMoKS5yZWR1Y2VkKDI0LCAxNik7CiAgICBjb25zdGV4cHIgaW50IHJvd0ggPSAzMiwgbGFiZWxXID0gMTYwLCBnYXAgPSAxMiwgY29udHJvbFcgPSAzNjA7CgogICAgYXV0byByb3cgPSBbJl0oanVjZTo6TGFiZWwmIGxhYmVsLCBqdWNlOjpDb21wb25lbnQmIGNvbnRyb2wpCiAgICB7CiAgICAgICAgYXV0byByID0gYXJlYS5yZW1vdmVGcm9tVG9wKHJvd0gpOwogICAgICAgIGxhYmVsLnNldEJvdW5kcyhyLnJlbW92ZUZyb21MZWZ0KGxhYmVsVykpOwogICAgICAgIGNvbnRyb2wuc2V0Qm91bmRzKHIucmVtb3ZlRnJvbUxlZnQoanVjZTo6am1pbihyLmdldFdpZHRoKCksIGNvbnRyb2xXKSkpOwogICAgICAgIGFyZWEucmVtb3ZlRnJvbVRvcChnYXApOwogICAgfTsKCiAgICByb3codmlld0xhYmVsLCB2aWV3Q29tYm8pOwoKICAgIGF1dG8gdG9nZ2xlUm93ID0gYXJlYS5yZW1vdmVGcm9tVG9wKHJvd0gpOwogICAgdG9nZ2xlUm93LnJlbW92ZUZyb21MZWZ0KGxhYmVsVyk7CiAgICB0aXRsZXNUb2dnbGUuc2V0Qm91bmRzKHRvZ2dsZVJvdy5yZW1vdmVGcm9tTGVmdChjb250cm9sVykpOwogICAgYXJlYS5yZW1vdmVGcm9tVG9wKGdhcCk7CgogICAgcm93KHZvbHVtZUxhYmVsLCB2b2x1bWVTbGlkZXIpOwp9Cn0='

if ($HadFailure) { exit 1 }
if (-not $DryRun -and $Manifest.Count -gt 0) {
    New-Item -ItemType Directory -Force -Path $BackupRoot | Out-Null
    Set-Content -LiteralPath $ManifestPath -Value $Manifest -Encoding UTF8
    Write-Host "OK MANIFEST: $ManifestPath" -ForegroundColor Green
}
Write-Host 'OK COMPLETE: Options view polish patch finished.' -ForegroundColor Green

